#!/bin/bash
closeParagraphIfOpened() {
    if [ $paragraphOpened -eq 1 ]
    then
        echo "</p>"
        paragraphOpened=0
    fi
}

read -r title

cat << EOF
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>$title</title>
</head>
<body>
EOF

paragraphOpened=0

while read -r line
do
    line=`echo "$line" | sed -e 's/.*%.*//'`
    line=`echo "$line" | sed -e 's/   */ /g'` # Фигачим вместо 2х и более пробелов 1	
    if [ ${#line} -gt 0 ]
    then
        if echo "$line" | grep "^\\\\section{.*}$" >/dev/null 2>&1
        then
            closeParagraphIfOpened
            line=${line:9}
            echo "<h1>${line:0:$[${#line} - 1]}</h1>"
        else
            if echo "$line" | grep "^\\\\subsection{.*}$" >/dev/null 2>&1
            then
                closeParagraphIfOpened
                line=${line:12}
                echo "<h2>${line:0:$[${#line} - 1]}</h2>"
            else
                if [ $paragraphOpened -eq 0 ]
                then
                    echo -n "<p>$line"
                    paragraphOpened=1
                else
                    echo ""
                    echo -n "$line"
                fi
            fi
        fi
    else
        closeParagraphIfOpened
    fi
done

closeParagraphIfOpened

cat << EOF
</body>
</html>
EOF

exit 0